%YAML 1.1
---
# - [ ] lodgingitems: units (must be int or string, not both as current)
paths:
  uploads: img
  static: static

_enabled_editors:
  - content

_editables:
  content:
    image_size_attributes: false
    blockquote: true
    link: true
    bold: true
    format: p h1 h2 h3
    italic: true
    strike: false
    subscript: false
    superscript: false
    underline: true
    bulletedlist: true
    indent: false
    numberedlist: true
    outdent: false
    code: false
    embed: true
    horizontalrule: false
    image: true
    table: true
    undo: true
    redo: true
    removeformat: true
    copyformatting: true

##########
# SIDEBAR
#########
collection_groups:
  - heading: Landing Pages
    collections:
      - main_pages
      - regular_pages
  - heading: Other
    collections:
      - adventures
      - posts
      - events
      - trip_ideas
      - stores
      - lodgings
      - tour_equipments
      - products
####################
#### COLLETIONS ####
###################
x-schema-base: &schema-base
  hide_extra_inputs: true
  remove_empty_inputs: true
  remove_extra_inputs: false
x-collection-base: &collection-base
  icon: article
  disable_add_folder: true
  filter:
    base: strict
  sort_options:
  - key: title
    order: asc
  - key: title
    order: desc
collections_config_override: true
collections_config:
  main_pages:
    <<: *collection-base
    path: content
    name: Main Pages
    icon: assignment_late
    description: This is where site's main pages go. Sections and homepages.
    schemas:
      default:
        <<: *schema-base
        path: .cloudcannon/schemas/regular-page.md
      home:
        <<: *schema-base
        icon: house
        path: .cloudcannon/schemas/home.md
      gallery:
        <<: *schema-base
        icon: collections
        path: .cloudcannon/schemas/gallery.md
    _inputs:
      welcomeheadline:
        label: Welcome Headline
        comment: Headline displayed below the slideshow
    filter:
      base: none
      include:
      - _index.md
      - index-es.md
      - adventures.md
      - calendar.md
      - dining.md
      - equipment-rent-and-buy.md
      - events.md
      - gallery.md
      - lodging.md
      - search.md
      - tour-guides-and-charters.md
  regular_pages:
    <<: *collection-base
    path: content/sitepages
    name: Regular Pages
    icon: tour
    filter:
      exclude:
      - _index.md
    schemas:
      default:
        <<: *schema-base
        path: .cloudcannon/schemas/regular-page.md
  posts:
    <<: *collection-base
    path: content/blog
    name: Blog Posts
    icon: article
    filter:
      exclude:
      - _index.md
    schemas:
      default:
        <<: *schema-base
        path: .cloudcannon/schemas/post.md
  adventures:
    <<: *collection-base
    path: content/adventure
    name: Adventures
    icon: hiking
    schemas:
      default:
        <<: *schema-base
        path: .cloudcannon/schemas/adventure.md
  products:
    <<: *collection-base
    path: content/products
    name: Products
    icon: local_offer
    image_key: image
    schemas:
      default:
        <<: *schema-base
        path: .cloudcannon/schemas/product.md
    filter:
      exclude:
        - _index.md
    _enabled_editors:
      - data
    _inputs:
      description:
        comment: Description of the product to be displayed on the web site
      product:
        type: object
        options:
          structures: _structures.products
  stores:
    <<: *collection-base
    path: content/store
    name: Shopping
    icon: store
    image_key: photo_name
    subtext_key: property_description
    schemas:
      default:
        <<: *schema-base
        path: .cloudcannon/schemas/store.md
    _enabled_editors:
      - data
    filter:
      exclude:
        - _index.md
  trip_ideas:
    <<: *collection-base
    path: content/tripideas
    name: Trip Ideas
    icon: tips_and_updates
    filter:
      exclude: 
      - _index.md
    schemas:
      default:
        <<: *schema-base
        path: .cloudcannon/schemas/trip-idea.md
    _inputs:
      photo:
        label: Header Photo
        comment: Choose a header image - size to 2048px by 530px
      towns:
        type: multiselect
        options:
          values: _select_data.towns
      adventures:
        type: multiselect
        options:
          values: _select_data.adventures
      durations:
        type: multiselect
        options:
          values: _select_data.durations
  lodgings:
    <<: *collection-base
    path: content/lodgingitems
    name: Lodging
    icon: hotel
    image_key: photo_name
    subtext_key: property_description
    _enabled_editors:
      - data
    filter:
      exclude: 
      - _index.md
    schemas:
      default:
        <<: *schema-base
        path: .cloudcannon/schemas/lodging.md
    _inputs:
      cost:
        type: select
        options:
          values:
          - 1 - $
          - 2 - $$
          - 3 - $$$
      property_category:
        type: select
        label: Category
        options:
          values:
          - 1 - Hotels, Motels & Inns
          - 2 - RV Parks & Camping
          - 3 - Bed & Breakfasts
          - 4 - Vacation Rental Homes
      amenityList:
        type: select
        label: Amenities
        options:
          values:
          - 1 - Restaurant/Bar/Rm Service
          - 2 - Continental or Full Bkfst
          - 3 - Fitness Center
          - 4 - Pool/Hot Tub
          - 5 - Pet Friendly
          - 6 - WiFi Available
          - 7 - Kitchens Available
          - 8 - Meeting Facilities
          - 9 - Handicap Accessible
          - 10 - Chamber Member
  tour_equipments:
    <<: *collection-base
    path: content/tourandequipment
    name: Tour & Equipments
    icon: festival
    _enabled_editors:
    - data
    filter:
      exclude: 
      - _index.md
    schemas:
      default:
        <<: *schema-base
        path: .cloudcannon/schemas/tour_equipment.md
    _inputs:
      property_name:
        label: Business Name for Sorting
      equip_type:
        type: multiselect
        label: Type
        options:
          values:
          - Tour
          - Equipment
  events:
    <<: *collection-base
    path: content/event
    name: Events
    icon: calendar_month
    subtext_key: startdate
    filter:
      exclude:
      - _index.md
    schemas:
      default:
        <<: *schema-base
        path: .cloudcannon/schemas/event.md
    sort_options:
    - key: startdate
      order: desc
      label: Start Date (Newest First)
    - key: startdate
      order: asc
      label: Start Date
    - key: title
      order: asc
####################
#### STRUCTURES ####
###################
_structures:
  accordion_sections:
    values:
      value:
        title:
        accordions:
  accordions:
    values:
      _inputs:
        content:
          label: Accordion Content
      value:
        title:
        content:
  ctas:
    values:
      _inputs:
        title: The text on the button
      value:
        title:
        url:
        action:
        image:
  masonry: &structure-masonry
    values:
      text_key: desktoptitle
      value:
        desktoptitle:
        desktopphoto:
        hovertitle:
        hoverdescription:
        mobiletitle:
        url:
  boxes: *structure-masonry
  home_splashes:
    values:
      _inputs:
        img:
          type: image
      value:
        url:
        img:
        alt:
  slideshow:
    values:
      _inputs:
        title:
          comment: The title of the slide
        photo:
          comment: The image of the slide
        title_mobile:
          comment: The text to be displayed on mobile
        photo_mobile:
          comment: The image used on mobile
        url:
          comment: The URL of the page opened when the slide is clicked
        video:
          type: object
          options:
            structures: _structures.videos
      value:
        title:
        photo:
        title_mobile:
        photo_mobile:
        url:
        video:
  videos:
    values:
      _inputs:
        cover:
          type: file
        source:
          type: file
      value:
        cover:
        source:
  custom_fields:
    style: modal
    id_key: id
    values:
    - label: Product Field Size
      _inputs:
        id:
          hidden: true
        options:
          type: array
      value:
        id: size
        name: Size
        options:
        - S
        - M
        - L
  products:
    values:
      _inputs:
        id: 
          comment: Will be used as product ID in the store back office
        price:
          type: number
        weight:
          type: number
          comment: The weight of the product in ounces
        description:
          comment: ''
      value:
        id:
        price:
        weight:
        description:
        custom_fields:

####################
#### INPUTS ####
###################
x-minimal-markdown: &input-minimal-markdown
  type: markdown
  options:
    bold: true
    italic: true
    undo: true
    redo: true
    link: false
x-input-markdown: &input-markdown
  type: markdown
x-input-hidden: &input-hidden
  hidden: true
x-input-image: &input-image
  type: image
_inputs:
  copy: *input-markdown
  content: *input-markdown
  description: *input-markdown
  template: *input-hidden
  draft:
    type: switch
  units:
    type: number
  tags:
    type: multiselect
    comment: Options are suggestions only, to add a tag, simply type it in the field.
    options:
      values: _select_data.tags
      allow_create: true
  aliases:
    type: multiselect
    options:
      values:
      - /blog/a-well-formated-url-example
      allow_create: true
  warning:
    type: switch
    comment: Should the post display the Blog's warning? 
  warning_copy:
    type: markdown
    hidden: warning
  url:
    type: text
  layout:
    label: Layout
    comment: Choose Layout/Sidebar for Your Page
  startdate: &textdate
    type: text
    label: Start Date
    comment: 'IMPORTANT: Date must be entered YYYY-MM-DD (NO Time)'
  enddate:
    <<: *textdate
    label: End Date
  ctas:
    type: array
    label: CTAs
    comment: Add CTAs to be invoked with the 'ctas' shortcode or else.
  property_category:
    type: multiselect
    options:
      values: _select_data.property_categories
  website:
    type: url
    comment: Website's URL. Must include protocole (https://)
  boxes:
    label: Masonry Items
    type: array
  desktoptitle: &responsive_title
    type: text
    label: Title for Desktop
  mobiletitle:
    <<: *responsive_title
    label: Title for Mobile
  hovertitle:
    <<: *responsive_title
    label: Box Animation Title
    comment: Title displayed on Event box animation
  photo:
    type: image
    label: Page Hero Image
    comment: Image Size 2048px x 530px
  photo_mobile: *input-image
  mobilephoto:
    <<: *input-image
    label: Mobile Photo
  desktopphoto: 
    <<: *input-image
    label: Desktop Photo
  photo_name:
    type: image
    label: Image
  photo_alt:
    label: Image Alternate Attribute
  largeboxphoto:
    type: image
    label: Large
    comment: Image Size 1024px x 395px
  mediumboxphoto:
    type: image
    label: Medium
    comment: Image Size 667px x 355px
  smallboxphoto:
    type: image
    label: Small
    comment: Image Size 340px x 214px
  hoverdescription:
    type: textarea
    label: Box Animation Description
    comment: Description displayed on Event Box animation
  slideshow:
    type: array
    options:
      image_key: photo
      structures: _structures.slideshow
  home_slashes:
    type: array
    options:
      structures: _structures.home_slashes
  masonry1: &input-masonry
    type: object
    text_key: desktoptitle
    options:
      structures: _structures.masonry
  masonry2: *input-masonry
  masonry3: *input-masonry
  masonry4: *input-masonry
  masonry5: *input-masonry
  masonry6: *input-masonry
  masonry7: *input-masonry
  gallery:
    type: array
    options:
      structures:
        values:
          value:
            title:
            image:
  seo:
    type: object
    options:
      structures:
        values:
          _inputs:
            imgalt:
              label: Image Alternative Text
            description: *input-minimal-markdown
          value:
            title:
            description:
            imgalt:
            image:

  address:
    type: object
    options:
      structures:
        values:
          value:
            street:
            city:
            zip:
  coordinates:
    type: object
    options:
      structures:
        values:
          _inputs:
            lat:
              label: Latitude
            lng:
              label: Longitude
          value:
            lat:
            lng:
_select_data:
  layouts:
  - contact
  - adventures
  - calendarpage
  - eventspage
  - gallery
  - search
  - meeting-planners
  - meeting-planners-sub
  - our-area
  - press-media-industry
  - open-meetings
  - relocation-request
  - thank-you
  - travelersinfo
  - lodgingpage
  - diningpage
  - equipment
  - headless
  - home
  - nosidebar
  categories:
  - Arts & Culture
  - Clamming
  - Crabbing
  - Fishing
  - Itineraries
  - Local Food & Drink
  - Local Spotlight
  - Miscellaneous
  - Oregon's Adventure Coast News & Info
  - Outdoor Adventures
  - Shopping & Entertainment
  - Special Events & Holidays
  - State Parks & National Lands
  property_categories:
  - Antiques
  - Arts & Crafts
  - Bookstores
  - Boutique
  - Clothing
  - Fitness
  - Florist
  - Groceries
  - Hardware
  - Herbals
  - Home Goods
  - Personal services
  - Pet Products
  - Pharmacy
  - Resale
  - Shoes
  - Souvenirs
  - Specialty Foods
  - Sporting Goods
  - Vitamins
  - Liquor Stores/ Growler Fills
  - Wellness
  towns:
  - charleston
  - coos-bay
  - north-bend
  adventures:
  - atving-motorsports
  - beach
  - crabbing-clamming
  - culture-museums
  - dunes
  - eat-drink
  - fishing
  - fishing-crabbing-clamming
  - historical
  - lighthouses
  - scenic-drives
  - shopping
  - state-parks-national-lands
  durations:
  - full-day
  - half-day
  - long-weekend
  tags:
  - something
  - other