---
baseurl: https://www.oregonsadventurecoast.com
languageCode: en-us
title: Oregon's Adventure Coast
googleAnalytics: UA-4406033-1
MetaDataFormat: yaml
disableAliases: true
mediaTypes:
  text/netlify:
    delimiter: ''
    suffixes:
    - ''
outputFormats:
  REDIR:
    baseName: _redirects
    isPlainText: true
    mediatype: text/netlify
    notAlternative: true
outputs:
  home:
  - HTML
  - RSS
  - REDIR
  - JSON
  section:
  - HTML
  - RSS
taxonomies:
  category: categories
  tag: tags
  duration: durations
  town: towns
  tripadventure: tripadventures
permalinks:
  adventure: ":slug/"
  sitepages: ":slug/"
  products: "/shop/:slug"
blackfriday:
  hrefTargetBlank: false
caches:
  getresource:
    maxAge: 12h
