baseUrl: 'https://www.oregonsadventurecoast.com'
removeAccents: true
disableKinds:
- sitemap
- section
markup:
  goldmark:
    renderer:
      unsafe: true
outputs:
  home:
  - json
  - yaml
caches:
  getresource:
    maxAge: 0
outputFormats:
  yaml:
    mediaType: 'application/yaml'
module:
  mounts:
  - source: content
    target: content
  - source: ../content
    target: content
    # In case some files breaks the import:
    excludeFiles:
    # Sports facilities page is breaking export... not sure why.
    - sitepages/sports-facilities.md
    # those articles's markdown includes a '/' after an html closing tag (</a>/).
    # This messes up the json to ndjson script...
    - blog/2017-08-16-bay-area-fun-festival-in-coos-bay-oregon.md
    - blog/blogmill-luck-salmon-celebration-returns-to-oregon-s-adventure-coast.md
    - blog/book-your-2018-holiday-lights.md
    - blog/countdown-to-the-2023-annular-solar-eclipse.md
    - blog/eleven-epic-sunsets-captured-on-oregon-s-adventure-coast.md
  - source: layouts
    target: layouts
  - source: data
    target: data
  - source: ../data
    target: data

taxonomies:
  category: categories
  tag: tags
  duration: durations
  town: towns
  tripadventure: tripadventures

params:
  domain: 'https://www.oregonsadventurecoast.com'
  #skip_assets: true
  #skip_relationships: true